---
# tasks file for k8s-master

- name: "Configuring yum repository"
  yum_repository:
    name: kubernetes
    description: kubernetes.repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-e17-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg 
    exclude: kubelet kubeadm kubectl

- name: "Installing Softwares"
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop:
    - iproute-tc
    - kubelet
    - kubeadm
    - kubectl
    - docker

- name: "Starting services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker
    - kubelet

- name: "Pulling images"
  shell: "kubeadm config images pull"
  changed_when: false
- name: "Changing driver in docker"
  copy:
    content: |
            {
               "exec-opts": [native.cgroupdriver=systemd]
            }
    dest: /etc/docker/daemon.json
  register: x

- name: "Restarting docker"
  service:
    name: docker
    state: restarted 
  when: x.changed == true

- name: "Updating config file"
  copy: 
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1

- name: "Initializing mAaster"
  shell: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem --node-name=master"
  ignore_errors: yes

- name: "Creating .kube directory"
  file:
    path: $HOME/.kube 
    state: directory

- name: "copy admin file"
  copy:
    remote_src: yes
    src: /etc/kubernets/admin.conf
    dest: $HOME/.kube/config

- name: "Change owner of .kube/config"
  file:
    path: $HOME/.kube/config
    owner: "{{ user-id }}"
    group: "{{ group-id }}"

- name: "flannel install"
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  changed_when: false

- name: "Getting Token"
  shell: "kubeadm token create --print-join-command"
  register: token
  ignore_errors: yes

- debug:
    var: token.stdout_lines
    register: token 

- add_host:
    name: "linktojoin"
    link: "{{ token['stdout'] }}"  
